apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-x5mc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-x5mc@sha256:594021df1de0a5f4295fe3f7b5061c96bc67dfbf1c30079f0f89d9243dacdfac
        name: my-nodejs
        resources: {}
status: {}
