apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-x5mc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-x5mc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0026-app
  name: devfile-sample-x5mc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-x5mc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-x5mc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-x5mc@sha256:594021df1de0a5f4295fe3f7b5061c96bc67dfbf1c30079f0f89d9243dacdfac
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
